version: '3.4'
volumes:
  dbdata:
services:
  db:
    image: postgres:11-alpine
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=developmentpassword

  redis:
    image: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - dfedigital/register-trainee-teachers:${BRANCH_TAG:-latest}
    image: dfedigital/register-trainee-teachers:${BRANCH_TAG:-latest}
    command: ash -c "bundle exec rails server -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - REDIS_URL=redis://redis:6379

  bg-jobs:
    image: dfedigital/register-trainee-teachers:${BRANCH_TAG:-latest}
    command: bundle exec sidekiq -c 5 -C config/sidekiq.yml
    depends_on:
      - web
      - db
      - redis
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - SETTINGS__APPLICATION=register-trainee-teachers-bg-jobs
      - REDIS_URL=redis://redis:6379
