default: &default
  RAILS_SERVE_STATIC_FILES: true

qa:
  <<: *default
  RAILS_ENV: qa
  RACK_ENV: qa

staging:
  <<: *default
  RAILS_ENV: staging
  RACK_ENV: staging

production:
  <<: *default
  RAILS_ENV: production
  RACK_ENV: production

review:
  <<: *default
  RAILS_ENV: review
  RACK_ENV: review

pen:
  <<: *default
  RAILS_ENV: pen
  RACK_ENV: pen
