# frozen_string_literal: true

PUBLISH_COURSES_WITH_SUBJECTS = {
  "Primary" => ["Primary"],
  "Art and design" => ["Art and design"],
  "Biology" => ["Biology"],
  "Chemistry" => ["Chemistry"],
  "Computing" => ["Computing"],
  "Design and Technology" => ["Design and technology"],
  "English" => ["English"],
  "Geography" => ["Geography"],
  "History" => ["History"],
  "Mathematics" => ["Mathematics"],
  "Modern Languages" => ["Modern languages (other)"],
  "Music" => ["Music"],
  "Physical Education" => ["Physical education"],
  "Physics" => ["Physics"],
  "Primary with Mathematics" => ["Primary with mathematics"],
  "Religious Education" => ["Religious education"],
  "Art and Design" => ["Art and design"],
  "Business Studies" => ["Business studies"],
  "Drama" => ["Drama"],
  "Health and Social Care" => ["Health and social care"],
  "Modern languages" => ["Modern languages (other)"],
  "PE with EBacc" => ["Physical education"],
  "Primary (SEND)" => ["Primary"],
  "Psychology" => ["Psychology"],
  "Religious education" => ["Religious education"],
  "Social Sciences" => ["Social sciences"],
  "Modern Languages (French and Spanish)" => %w[French Spanish],
  "Computer Science" => ["Computing"],
  "Design and technology" => ["Design and technology"],
  "Modern Languages (Spanish)" => ["Spanish"],
}.freeze
